
    <h1><?php echo $label; ?></h1>
    <hr/>

    <div class="form-group">
        <label for="">System Time Zone</label>
        <input type="text" class="form-control" value="<?php echo ini_get('date.timezone'); ?>" readonly="readonly">
    </div>

    <div class="form-group">
        <label for="">Time by System Environment</label>
        <input type="text" class="form-control" value="<?php echo date("Y-m-d H:i:s (w)"); ?>" readonly="readonly">
    </div>

    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-11">

            <?php ini_set('date.timezone','Europe/London'); ?>
            <div class="form-group">
                <label for="">by "<?php echo ini_get('date.timezone'); ?>" (UTC +0) </label>
                <input type="text" class="form-control" value="<?php echo date("Y-m-d H:i:s (w)"); ?>" readonly="readonly">
            </div>

            <?php ini_set('date.timezone','Asia/Taipei'); ?>
            <div class="form-group">
                <label for="">by "<?php echo ini_get('date.timezone'); ?>"</label>
                <input type="text" class="form-control" value="<?php echo date("Y-m-d H:i:s (w)"); ?>" readonly="readonly">
            </div>

            <?php ini_set('date.timezone','America/Los_Angeles'); ?>
            <div class="form-group">
                <label for="">by "<?php echo ini_get('date.timezone'); ?>"</label>
                <input type="text" class="form-control" value="<?php echo date("Y-m-d H:i:s (w)"); ?>" readonly="readonly">
            </div>
            <span>※如果以上的 timezone 都相同, 表示該 "主機" 無法使用 ini_set() 命令</span>

        </div>
    </div>

    <div class="form-group">
        <label for="">Server API</label>
        <input type="text" class="form-control" value="<?php echo php_sapi_name(); ?>" readonly="readonly">
        
    </div>
    <span>※Apache *.* Handler => mod_php</span>

