<?php

    $isLoaded = 'No';
    $version = '?';
    if ( extension_loaded('phalcon') ) {

        $isLoaded = 'Yes';
        $version = Phalcon\Version::get();

    }

?>

    <h1><?php echo $label; ?></h1>
    <hr/>

    <div class="form-group">
        <label for="">Load Phalcon extension</label>
        <input type="text" class="form-control" value="<?php echo $isLoaded; ?>" readonly="readonly">
    </div>

    <div class="form-group">
        <label for="">Phalcon version</label>
        <input type="text" class="form-control" value="<?php echo $version; ?>" readonly="readonly">
    </div>
