
<script type="text/javascript" charset="utf-8">
    "use strict";
    $(function() {
        // checkbox all
        aid.event.checkboxAll('#chooseItemsAll');
    });
</script>

<div class="row">
    <div class="col-md-3">
        <form name="form-search" id="form-search" class="form-inline" method="get" action="" >
            <div class="input-group">
                <input type="text" class="form-control" placeholder="search keyword" name="searchKey" value="<?php echo $searchKey; ?>" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>
<br/>

<form name="form-index" id="form-index" method="post" >

    <table id="table-index" class="table table-striped table-condensed table-bordered">
        <thead>
            <tr>
                <th style="width:15px;"><input class="checkbox" type="checkbox" id="chooseItemsAll" value="1" /></th>
                <th>id</th>
                <th>表單名稱</th>
                <th>keyword</th>
                <th>狀態</th>
                <th>建立時間</th>
                <th>管理</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach( $formPages as $formPage ) {
            $showLink    = url('formpageContent', array('formPageId'=>$formPage->getId()));
            $settingLink = url('formpage/setting', array('formPageId'=>$formPage->getId()));
            $demoLink    = url('formpage/demo', array('formPageId'=>$formPage->getId()));
          //$demoLink    = url('public/formPage', Array('formPageId'=>$formPage->getId()));
            echo '<tr>';
            echo    '<th><input class="checkbox" type="checkbox" name="chooseItems[]" value="'. $formPage->getId() .'"></th>';
            echo     '<td>'. $formPage->getId() .'</td>';
            echo     '<td>';
            echo         '<a href="'. $showLink .'"><div class="fam-application-go"></div>'. $formPage->getName() .'</a>';
            echo     '</td>';
            echo     '<td>'. $formPage->getKeyword() .'</td>';
            echo     '<td>';
                        if( $formPage->getStatus() ) {
                            echo '啟用';
                        }
                        else {
                            echo '停用';
                        }
            echo     '</td>';
            echo     '<td>'. cc('date',$formPage->getCreateTime()) .'</td>';
            echo     '<td>';
            echo         '<a href="'. $settingLink .'"><div class="fam-cog"></div>設定</a> ';
            echo         '<a href="'. $demoLink    .'"><div class="fam-book-open"></div>Demo</a> ';
            echo     '</td>';
            echo '</tr>';
        } ?>
        </tbody>
    </table>

    <?php echo cc('displayPageLimit', $pageLimit ); ?>

</form>

